ecmaFeatures:
  modules: true
  spread: true
  restParams: true
env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: "eslint:recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
rules:
  no-fallthrough: off
  no-console: off
  no-restricted-syntax:
    - warn
    - selector: CallExpression[callee.object.name='console'][callee.property.name!=/^(warn|error|trace|log)$/]
      message: "Unexpected property on console object was called"
  max-len:
    - warn
    - code: 160
      tabWidth: 4
      ignoreComments: false
      ignoreTrailingComments: false
  no-unused-vars: off
  no-process-env: off
  # indent:
  #   - warn
  #   - 4
  linebreak-style:
    - off
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
